# Generated by Django 3.1.2 on 2020-11-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_splashscreen_splashscreenpreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='answer',
            new_name='true_answer',
        ),
    ]
