# Generated by Django 3.1.2 on 2020-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201119_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='number_of_correct_answers',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='score',
            name='number_of_incorrect_answers',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_questions_answered',
            field=models.IntegerField(default='0'),
        ),
    ]
