# Generated by Django 3.1.2 on 2020-11-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_splashscreen_splashscreenpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplashScreen',
        ),
        migrations.DeleteModel(
            name='SplashScreenPreference',
        ),
    ]
